import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/lib/logging", () => ({
  createLogger: () => ({
    info: vi.fn(),
    debug: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
  }),
}));

import { createJobsRepo, type JobsRepo } from "./repo";
import {
  _createTestDb,
  _installTestDb,
  _resetForTesting,
} from "../state-store/state-db";
import { jobRecordSchema } from "./schemas";
import type { JobRecord } from "./schemas";
import { assertRoundTripDurability } from "@/lib/shared/testing/round-trip-durability";

let repo: JobsRepo;

beforeEach(() => {
  const db = _createTestDb({ inMemory: true });
  _installTestDb(db);
  repo = createJobsRepo(db);
});

afterEach(() => {
  _resetForTesting();
});

/**
 * Build a durable job record with EVERY persisted key path of the strict
 * `jobRecordSchema` populated to a distinctive non-default value, so the
 * schema-driven durability harness can prove no column — including the optional
 * terminal metadata (`completedAt`, `mergeHash`, `commitHash`, `conflictCount`,
 * `errorMessage`), final-publish identity, the parked-merge bookkeeping a land
 * re-entry reconstructs its input from, and the JSON-encoded `conflictFiles`
 * column — is dropped on write or reset to its default on read.
 *
 * `status` is a TERMINAL value (`completed`) so the update write path that
 * carries the terminal metadata is exercised. `conflictFiles` carries multiple
 * elements so its JSON serialization is checked. `completedAt` is GENERATED by
 * `updateJobRecord` (SQLite `datetime('now')`), so the fixture seeds a
 * placeholder string to satisfy the completeness guard; the real generated value
 * is established by the accessor-read `expected` in `persist()` (see the
 * `derived-on-write` policy below).
 */
function buildMaximalJobRecord(): JobRecord {
  return jobRecordSchema.parse({
    jobId: "job-maximal",
    jobType: "merge",
    status: "completed",
    projectName: "maximal-project",
    sessionName: "maximal-session",
    branchName: "csm/maximal-session",
    startedAt: "2026-01-01 00:00:00",
    completedAt: "placeholder-completed-at",
    mergeHash: "merge-hash-abc123",
    commitHash: "commit-hash-def456",
    conflictCount: 2,
    conflictFiles: ["src/alpha.ts", "src/beta.ts"],
    errorMessage: "Auto-merge halted on overlapping edits",
    executionId: "workflow-execution-maximal",
    finalPublish: true,
    parkedRef: "refs/cc-merges/job-maximal",
    preparedSha: "prepared-sha-abc123",
    expectedTargetSha: "expected-target-sha-def456",
    finalizeSessionOnPublish: true,
    resolutionContext: "Kept the session's rename; main only reformatted.",
    candidateValidation: {
      validationRef: "validation-maximal",
      validatedSha: "validated-sha-abc123",
      validatedTreeHash: "validated-tree-def456",
      commandIdentity: "./scripts/pre-merge.sh",
      outcome: "pass",
    },
  });
}

/**
 * `completedAt` is generated by `updateJobRecord` (SQLite `datetime('now')`), so
 * it is validated for presence/non-default against the accessor-read `expected`
 * returned by `persist()` rather than the placeholder seeded in the fixture.
 */
const fieldPolicies = {
  completedAt: "derived-on-write",
} as const;

describe("job-records durability contract", () => {
  it("round-trips every persisted durable job-record key path through the real repo", async () => {
    expect(Object.keys(jobRecordSchema.shape)).toEqual(
      expect.arrayContaining([
        "executionId",
        "finalPublish",
        "candidateValidation",
        "parkedRef",
        "preparedSha",
        "expectedTargetSha",
        "finalizeSessionOnPublish",
        "resolutionContext",
      ]),
    );
    await assertRoundTripDurability({
      label: "job-records",
      schema: jobRecordSchema,
      buildMaximalFixture: buildMaximalJobRecord,
      persist: (fixture) => {
        // createJobRecord only sets the create-time columns and inserts as
        // running; the terminal status and metadata reach their columns via
        // updateJobRecord, which also generates completedAt.
        repo.createJobRecord({
          jobId: fixture.jobId,
          jobType: fixture.jobType,
          status: "running",
          projectName: fixture.projectName,
          sessionName: fixture.sessionName,
          branchName: fixture.branchName,
          startedAt: fixture.startedAt,
          executionId: fixture.executionId,
          finalPublish: fixture.finalPublish,
          finalizeSessionOnPublish: fixture.finalizeSessionOnPublish,
          resolutionContext: fixture.resolutionContext,
          candidateValidation: fixture.candidateValidation,
        });
        repo.updateJobRecord(fixture.jobId, {
          status: fixture.status,
          ...(fixture.mergeHash !== undefined
            ? { mergeHash: fixture.mergeHash }
            : {}),
          ...(fixture.commitHash !== undefined
            ? { commitHash: fixture.commitHash }
            : {}),
          ...(fixture.conflictCount !== undefined
            ? { conflictCount: fixture.conflictCount }
            : {}),
          ...(fixture.conflictFiles !== undefined
            ? { conflictFiles: fixture.conflictFiles }
            : {}),
          ...(fixture.errorMessage !== undefined
            ? { errorMessage: fixture.errorMessage }
            : {}),
          ...(fixture.executionId !== undefined
            ? { executionId: fixture.executionId }
            : {}),
          ...(fixture.parkedRef !== undefined
            ? { parkedRef: fixture.parkedRef }
            : {}),
          ...(fixture.preparedSha !== undefined
            ? { preparedSha: fixture.preparedSha }
            : {}),
          ...(fixture.expectedTargetSha !== undefined
            ? { expectedTargetSha: fixture.expectedTargetSha }
            : {}),
          ...(fixture.candidateValidation !== undefined
            ? { candidateValidation: fixture.candidateValidation }
            : {}),
        });
        const expected = repo.getJobRecord(fixture.jobId);
        if (expected === null) {
          throw new Error(
            "job-records contract: getJobRecord returned null after create+update",
          );
        }
        return expected;
      },
      reload: (expected) => repo.getJobRecord(expected.jobId),
      fieldPolicies,
    });
  });
});
