import { z } from "zod";

export const buildInfoSchema = z.object({
  sha: z.string().min(1),
  buildTime: z.string().min(1),
});

export type BuildInfo = z.infer<typeof buildInfoSchema>;

/**
 * The stamp identifies one build of the server/CLI pair. It travels in the
 * X-CC-CLI-Build header and `cctl --version` output, so it must stay a
 * single header-safe token (no spaces).
 */
export function formatBuildStamp(info: BuildInfo): string {
  return `${info.sha}-${info.buildTime}`;
}

/**
 * Render the generated build-info module source. Written by
 * scripts/generate-build-info.ts to src/lib/build-info/build-info.generated.ts
 * (gitignored); both the server and the cctl bundle import it so they share
 * one stamp per build.
 */
export function renderBuildInfoModule(info: BuildInfo): string {
  return `// Generated by scripts/generate-build-info.ts — do not edit.
import type { BuildInfo } from "./stamp";

export const BUILD_INFO: BuildInfo = {
  sha: ${JSON.stringify(info.sha)},
  buildTime: ${JSON.stringify(info.buildTime)},
};
`;
}
