export const TICKET_RELATIONSHIP_OUTLINE_LIMIT = 20;
export const TICKET_STATUS_UPDATE_RECENT_LIMIT = 5;
export const RELATIONSHIP_DESCRIPTION_PREVIEW_CHARS = 120;
export const STATUS_UPDATE_BODY_PREVIEW_CHARS = 160;
export const TICKET_PAGE_DEFAULT_LIMIT = 20;
export const TICKET_PAGE_MAX_LIMIT = 100;
